- name: manage zabbix redis userparameter
  template:
    src: 'templates/userparameter_redis.conf'
    dest: '{{ zabbix_dir }}/userparameter_redis.conf'
    owner: root
    group: root
    mode: 0644
  notify: 'restart zabbix-agent'

- name: Import Zabbix json template configuration
  local_action:
    module: zabbix_template
    server_url: '{{ zabbix_url }}'
    login_user: '{{ zabbix_user}}'
    login_password: '{{ zabbix_pass }}'
    template_name: Template App Redis
    template_json: "{{ lookup('file', 'templates/zabbix_redis.json') }}"
    template_groups:
      - Templates
    state: present
  ignore_errors: yes

- name: Link host to template
  local_action:
    module: zabbix_host
    server_url: '{{ zabbix_url }}'
    login_user: '{{ zabbix_user}}'
    login_password: '{{ zabbix_pass }}'
    host_name: '{{ ansible_fqdn }}'
    force: no
    link_templates:
      - Template App Redis
  ignore_errors: yes
